# Markdownlint configuration file
default: true,
line-length: false
no-bare-urls: false # tools only - the {{ jinja variables }} break URLs and cause this to error
commands-show-output: false # tools only - suppresses error messages for usage of $ in main README
