sudo: required
language: python
jdk: openjdk8
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
  # Install Nextflow
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Set up nf-core and test/coverage modules
  - cd ${TRAVIS_BUILD_DIR}
  - pip install .
  - pip install codecov pytest pytest-datafiles pytest-cov mock

script: python -m pytest --cov=nf_core .

after_success:
  - codecov
