language: python
sudo: false

python:
  - "2.7"

install:
  - pip install codecov
  - pip install -r requirements.txt

script: 
  - nosetests --with-coverage

after_success:
  - codecov

# safelist
branches:
  only:
  - master
