[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=40.6.0",
    "wheel"
]

[tool.black]
line-length = 120
target_version = ["py37", "py38", "py39", "py310"]

[tool.pytest.ini_options]
markers = [
    "datafiles: load datafiles"
]
testpaths = ["tests"]
norecursedirs = [ ".*", "build", "dist", "*.egg", "data", "__pycache__", ".github", "nf_core", "docs"]

[tool.ruff]
line-length = 120
target-version = "py38"
ignore = ["E501"]

[tool.ruff.isort]
known-first-party = ["nf_core"]
