name: Test successful pipeline download with 'nf-core download'

# Run the workflow when:
#  - dispatched manually
#  - when a PR is opened or reopened to master branch
#  - the head branch of the pull request is updated, i.e. if fixes for a release are pushed last minute to dev.

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - master
  pull_request_target:
    branches:
      - master

env:
  NXF_ANSI_LOG: false

jobs:
  download:
    runs-on: ["self-hosted"]
    steps:
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/nf-core/tools.git@dev

      - name: Get the repository name and current branch set as environment variable
        run: |
          echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          echo "REPOTITLE_LOWERCASE=$(basename ${GITHUB_REPOSITORY,,})" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${GITHUB_REF#refs/heads/}" >> ${GITHUB_ENV}

      - name: Download the pipeline
        env:
          NXF_SINGULARITY_CACHEDIR: ./
        run: |
          nf-core download {% raw %}${{ env.REPO_LOWERCASE }}{% endraw %} \
          --revision {% raw %}${{ env.REPO_BRANCH }}{% endraw %} \
          --outdir ./{% raw %}${{ env.REPOTITLE_LOWERCASE }}{% endraw %} \
          --compress "none" \
          --container-system 'singularity' \
          --container-library "quay.io" -l "docker.io" -l "ghcr.io" \
          --container-cache-utilisation 'amend' \
          --download-configuration

      - name: Inspect download
        run: tree ./{% raw %}${{ env.REPOTITLE_LOWERCASE }}{% endraw %}

      - name: Run the downloaded pipeline
        env:
          NXF_SINGULARITY_CACHEDIR: ./
          NXF_SINGULARITY_HOME_MOUNT: true
        run: nextflow run ./{% raw %}${{ env.REPOTITLE_LOWERCASE }}{% endraw %}/$( sed 's/\W/_/g' <<< {% raw %}${{ env.REPO_BRANCH }}{% endraw %}) -stub -profile test,singularity --outdir ./results
