name: "Close user-tagged issues and PRs"
on:
  schedule:
    - cron: "30 1 * * 7" # Once a week

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-message: "This issue has been tagged as stale by an nf-core contributor. Remove stale label or add a comment otherwise this issue will be closed in 20 days."
          stale-pr-message: "This PR has been tagged as stale by an nf-core contributor. Remove stale label or add a comment if it is still useful. Otherwise, this PR will be automatically closed."
          close-issue-message: "This issue was closed because it has been tagged as stale by an nf-core contributor and then staled for 20 days with no activity."
          days-before-stale: 30
          days-before-close: 20
          days-before-pr-close: -1
          any-of-labels: "awaiting-changes,awaiting-feedback"
          exempt-issue-labels: "WIP"
          exempt-pr-labels: "WIP"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
