image: nfcore/gitpod:latest
tasks:
  - name: Update Nextflow and setup pre-commit
    command: |
      pre-commit install --install-hooks
      nextflow self-update {%- if code_linters %}

vscode:
  extensions:
    - nf-core.nf-core-extensionpack {%- endif -%}
