# Config file for Python. Mostly used to configure linting of bin/check_samplesheet.py with Ruff.
# Should be kept the same as nf-core/tools to avoid fighting with template synchronisation.
[tool.ruff]
line-length = 120
target-version = "py38"
ignore = ["E501"]

[tool.ruff.isort]
known-first-party = ["nf_core"]
