name: {{ cookiecutter.name_noslash }}-{{ cookiecutter.version }}
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - fastqc=0.11.7
  - multiqc=1.6
