###################################################################################
##################################### WARNING #####################################
###################################################################################
## If using DSL2 then you no longer need this file.                              ##
##                                                                               ##
## All Conda dependencies can be installed by a combination of using:            ##
##   - The Nextflow 'conda' directive to list conda package requirements         ##
##   - The Nextflow 'container' directive to list Docker / Singularity images    ##
##     hosted by Biocontainers                                                   ##
##                                                                               ##
## See an example implementation of FastQC on nf-core/modules:                   ##
## https://github.com/nf-core/modules/blob/master/software/fastqc/main.nf        ##
###################################################################################

# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: {{ cookiecutter.name_noslash }}-{{ cookiecutter.version }}
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.9