name: Create a pipeline and run nf-core linting
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "docs/**"
      - "CHANGELOG.md"
  pull_request:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      runners:
        description: "Runners to test on"
        type: choice
        options:
          - "ubuntu-latest"
          - "self-hosted"
        default: "self-hosted"

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NXF_ANSI_LOG: false

jobs:
  MakeTestWorkflow:
    runs-on: ${{ github.event.inputs.runners || github.run_number > 1 && 'ubuntu-latest' || 'self-hosted' }}
    env:
      NXF_ANSI_LOG: false
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: go to subdirectory and change nextflow workdir
        run: |
          mkdir -p create-lint-wf
          cd create-lint-wf
          export NXF_WORK=$(pwd)

      # Get the repo code
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        name: Check out source-code repository

      # Set up nf-core/tools
      - name: Set up Python 3.11
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: run create-lint-wf
        uses: ./.github/actions/create-lint-wf
        with:
          NXF_VER: ${{ matrix.NXF_VER }}

      - name: Cleanup work directory
        run: sudo rm -rf create-lint-wf
        if: always()

