name: Run isort
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source-code repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip -r requirements-dev.txt
          pip install -e .

      - name: Install isort
        run: pip install isort

      - uses: jamescurtin/isort-action@master
        with:
          configuration: "--profile black"
          requirementsFiles: "requirements.txt requirements-dev.txt"
