name: Sync template
on:
  release:
    types: [published]

jobs:
  sync-all:
    name: Sync all pipelines
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install Nextflow
        run: |
          mkdir /tmp/nextflow
          cd /tmp/nextflow
          wget -qO- get.nextflow.io | bash
          sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow

      - name: Run synchronisation
        if: github.repository == 'nf-core/tools'
        env:
          AUTH_TOKEN: ${{ secrets.nf_core_bot_auth_token }}
        run: |
          git config --global user.email "core@nf-co.re"
          git config --global user.name "nf-core-bot"
          nf-core --log-file sync_log.txt sync --all --username nf-core-bot --auth-token $AUTH_TOKEN

      - name: Upload sync log file artifact
        uses: actions/upload-artifact@v2
        with:
          name: sync-log-file
          path: sync_log.txt
